# Generated by Django 6.0.3 on 2026-03-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_cliente_nombre_alter_producto_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='direccion',
            field=models.TextField(),
        ),
    ]
