# Generated by Django 6.0.3 on 2026-03-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_tienda_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_de_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
