# Generated by Django 6.0.3 on 2026-03-27 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_libro'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='isbn',
            field=models.CharField(default='0000000000000', max_length=13),
        ),
    ]
