# Generated by Django 6.0.3 on 2026-03-27 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_libro_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='isbn',
        ),
    ]
